packageExtensions:
  eslint-config-react-app@7.0.1:
    dependencies:
      '@babel/plugin-syntax-flow': '*'
      '@babel/plugin-transform-react-jsx': '*'
  react-dev-utils@12.0.1:
    dependencies:
      typescript: '*'
      webpack: '*'
  '@craco/craco@6.4.3':
    dependencies:
      '@types/node': '*'
      typescript: '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-3.2.1.cjs
