packageExtensions:
  eslint-config-react-app@7.0.1:
    dependencies:
      '@babel/plugin-syntax-flow': '*'
      '@babel/plugin-transform-react-jsx': '*'
  react-dev-utils@12.0.1:
    dependencies:
      typescript: '*'
      webpack: '*'
  '@devtools-ds/themes@1.2.0':
    dependencies:
      react-dom: '*'
  '@storybook/addon-docs@6.5.9':
    dependencies:
      '@babel/core': '*'
      webpack: '*'
  '@storybook/docs-tools@6.5.9':
    dependencies:
      react: '*'
      react-dom: '*'
  '@storybook/instrumenter@6.5.9':
    dependencies:
      react: '*'
      react-dom: '*'
  '@storybook/mdx1-csf@0.0.1':
    dependencies:
      '@babel/core': '*'
  '@storybook/telemetry@6.5.9':
    dependencies:
      react: '*'
      react-dom: '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-3.2.1.cjs
